"""Update problem model

Revision ID: 3019536ec637
Revises: 638051b73280
Create Date: 2026-07-16 17:26:14.161923

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3019536ec637'
down_revision: Union[str, Sequence[str], None] = '638051b73280'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('problems', sa.Column('external_problem_id', sa.String(length=20), nullable=True))
    op.add_column('problems', sa.Column('category', sa.String(length=100), nullable=True))
    op.add_column('problems', sa.Column('problem_type', sa.String(length=100), nullable=True))
    op.add_column('problems', sa.Column('vc_stage', sa.String(length=100), nullable=True))
    op.alter_column('problems', 'name',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=500),
               existing_nullable=False)
    op.drop_index(op.f('ix_problems_name'), table_name='problems')
    op.create_index(op.f('ix_problems_name'), 'problems', ['name'], unique=True)
    op.create_index(op.f('ix_problems_category'), 'problems', ['category'], unique=False)
    op.create_index(op.f('ix_problems_external_problem_id'), 'problems', ['external_problem_id'], unique=True)
    op.create_index(op.f('ix_problems_problem_type'), 'problems', ['problem_type'], unique=False)
    op.drop_column('problems', 'description')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('problems', sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_problems_problem_type'), table_name='problems')
    op.drop_index(op.f('ix_problems_external_problem_id'), table_name='problems')
    op.drop_index(op.f('ix_problems_category'), table_name='problems')
    op.drop_index(op.f('ix_problems_name'), table_name='problems')
    op.create_index(op.f('ix_problems_name'), 'problems', ['name'], unique=False)
    op.alter_column('problems', 'name',
               existing_type=sa.String(length=500),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.drop_column('problems', 'vc_stage')
    op.drop_column('problems', 'problem_type')
    op.drop_column('problems', 'category')
    op.drop_column('problems', 'external_problem_id')
    # ### end Alembic commands ###
