"""Create remaining tables

Revision ID: 638051b73280
Revises: 13656e06f5b5
Create Date: 2026-07-16 17:12:31.656060

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '638051b73280'
down_revision: Union[str, Sequence[str], None] = '13656e06f5b5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('problems',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('severity', sa.String(length=50), nullable=True),
    sa.Column('financial_impact', sa.Text(), nullable=True),
    sa.Column('regulatory_trigger', sa.Text(), nullable=True),
    sa.Column('ai_solution', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_problems_name'), 'problems', ['name'], unique=False)
    op.create_index(op.f('ix_problems_severity'), 'problems', ['severity'], unique=False)
    op.create_table('sectors',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sectors_name'), 'sectors', ['name'], unique=True)
    op.create_table('company_sectors',
    sa.Column('company_id', sa.Uuid(), nullable=False),
    sa.Column('sector_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sector_id'], ['sectors.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('company_id', 'sector_id')
    )
    op.create_index('ix_company_sectors_sector_id_company_id', 'company_sectors', ['sector_id', 'company_id'], unique=False)
    op.create_table('news_articles',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('company_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('url', sa.String(length=1000), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_news_articles_company_id'), 'news_articles', ['company_id'], unique=False)
    op.create_index('ix_news_articles_company_id_published_at', 'news_articles', ['company_id', 'published_at'], unique=False)
    op.create_index(op.f('ix_news_articles_published_at'), 'news_articles', ['published_at'], unique=False)
    op.create_index(op.f('ix_news_articles_title'), 'news_articles', ['title'], unique=False)
    op.create_index(op.f('ix_news_articles_url'), 'news_articles', ['url'], unique=True)
    op.create_table('problem_company_mappings',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('company_id', sa.Uuid(), nullable=False),
    sa.Column('problem_id', sa.Uuid(), nullable=False),
    sa.Column('roi', sa.String(length=100), nullable=True),
    sa.Column('payback', sa.String(length=100), nullable=True),
    sa.Column('implementation_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['problem_id'], ['problems.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'problem_id', name='uq_problem_company_mappings_company_id_problem_id')
    )
    op.create_index(op.f('ix_problem_company_mappings_company_id'), 'problem_company_mappings', ['company_id'], unique=False)
    op.create_index(op.f('ix_problem_company_mappings_problem_id'), 'problem_company_mappings', ['problem_id'], unique=False)
    op.create_index('ix_problem_company_mappings_problem_id_company_id', 'problem_company_mappings', ['problem_id', 'company_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_problem_company_mappings_problem_id_company_id', table_name='problem_company_mappings')
    op.drop_index(op.f('ix_problem_company_mappings_problem_id'), table_name='problem_company_mappings')
    op.drop_index(op.f('ix_problem_company_mappings_company_id'), table_name='problem_company_mappings')
    op.drop_table('problem_company_mappings')
    op.drop_index(op.f('ix_news_articles_url'), table_name='news_articles')
    op.drop_index(op.f('ix_news_articles_title'), table_name='news_articles')
    op.drop_index(op.f('ix_news_articles_published_at'), table_name='news_articles')
    op.drop_index('ix_news_articles_company_id_published_at', table_name='news_articles')
    op.drop_index(op.f('ix_news_articles_company_id'), table_name='news_articles')
    op.drop_table('news_articles')
    op.drop_index('ix_company_sectors_sector_id_company_id', table_name='company_sectors')
    op.drop_table('company_sectors')
    op.drop_index(op.f('ix_sectors_name'), table_name='sectors')
    op.drop_table('sectors')
    op.drop_index(op.f('ix_problems_severity'), table_name='problems')
    op.drop_index(op.f('ix_problems_name'), table_name='problems')
    op.drop_table('problems')
    # ### end Alembic commands ###
